[latest]
title = "블로터 ─ 최신기사"
url = "https://www.bloter.net/newsList/blt000000000"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[popular]
title = "블로터 ─ 실시간 랭킹"
url = "https://www.bloter.net/newsList/popularArticle"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[business_top]
title = "블로터 ─ 비즈니스 ─ 헤드라인"
url = "https://www.bloter.net/section?id=sectionBusiness2"
entrySelector = "div.box.section_business_headline ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a.link"
contentSelector = "div.info"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[business]
title = "블로터 ─ 비즈니스"
url = "https://www.bloter.net/section?id=sectionBusiness2"
entrySelector = "div.box.section_business_newslist_3 ul.list li.article"
titleSelector = "a.link h4.title"
linkSelector = "a.link"
contentSelector = "div.info"
imageSelector = "div.thumb div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[tech_top]
title = "블로터 ─ 테크 ─ 헤드라인"
url = "https://www.bloter.net/section?id=sectionTech"
entrySelector = "div.box.section_tech_top ul.list li.article"
titleSelector = "h4.title"
linkSelector = "div.text_box a.link"
contentSelector = "div.info"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[tech]
title = "블로터 ─ 테크"
url = "https://www.bloter.net/section?id=sectionTech"
entrySelector = "div.box.section_tech_newslist ul.list li.article"
titleSelector = "a.link h4.title"
linkSelector = "a.link"
contentSelector = "div.info"
imageSelector = "div.thumb div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[tech_blockchain]
title = "블로터 ─ 테크 ─ 블록먼데이"
url = "https://www.bloter.net/newsList/blt_S000005"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[tech_techchanger]
title = "블로터 ─ 테크 ─ 테크체인저"
url = "https://www.bloter.net/newsList/blt_S000173"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[culture_top]
title = "블로터 ─ 컬처 ─ 헤드라인"
url = "https://www.bloter.net/section?id=sectionCulture"
entrySelector = "div.box.section_culture_top ul.list li.article"
titleSelector = "h4.title"
linkSelector = "div.text_box a.link"
contentSelector = "div.info"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[culture]
title = "블로터 ─ 컬처"
url = "https://www.bloter.net/section?id=sectionCulture"
entrySelector = "div.box.section_newslist2 ul.list li.article"
titleSelector = "a.link h4.title"
linkSelector = "a.link"
contentSelector = "div.desc"
imageSelector = "div.thumb div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[culture_ohculture]
title = "블로터 ─ 컬처 ─ 오~컬쳐"
url = "https://www.bloter.net/newsList/blt_S000022"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "a:nth-child(1) h4.title"
linkSelector = "a:nth-child(1)"
contentSelector = "a:nth-child(4) div.desc"
imageSelector = "div.thumb div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[culture_ottoriginal]
title = "블로터 ─ 컬처 ─ OTT오리지널"
url = "https://www.bloter.net/newsList/blt_S000171"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "a:nth-child(1) h4.title"
linkSelector = "a:nth-child(1)"
contentSelector = "a:nth-child(4) div.desc"
imageSelector = "div.thumb div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[finance]
title = "블로터 ─ 금융"
url = "https://www.bloter.net/newsList/blt001005000"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"

[class]
title = "블로터 ─ CLASS"
url = "https://www.bloter.net/newsList/blt_SC007000000"
entrySelector = "div.box.newslist_left ul.list li.article"
titleSelector = "h4.title"
linkSelector = "a"
contentSelector = "div.desc"
imageSelector = "div.background.zoom img"
waitUntil = "networkidle"
onFail = "stale"
